### ISSUE TITLE
build failing

### ISSUE THREAD

**Issue by int3hh** [Samourai-Wallet/samourai-wallet-android#318]
current tag does not build using android studio 3.4

**Comment by InvertedX** [comment]
can you share some logs.

**Comment by int3hh** [comment]
> :app:generateProductionDebugSources
:app:javaPreCompileProductionDebug
./samourai-wallet-android/app/src/main/java/com/samourai/stomp/client/AndroidStompClient.java:29: error: AndroidStompClient is not abstract and does not override abstract method subscribe(Map<String,String>,MessageErrorListener<IStompMessage,String>) in IStompClient
public class AndroidStompClient implements IStompClient {
       ^
./samourai-wallet-android/app/src/main/java/com/samourai/stomp/client/AndroidStompClient.java:39: error: method does not override or implement a method from a supertype
    @Override
    ^
./samourai-wallet-android/app/src/main/java/com/samourai/stomp/client/AndroidStompClient.java:81: error: method does not override or implement a method from a supertype
    @Override
    ^

**Comment by SamouraiDev** [comment]
Change gradle to:
implementation ('com.github.Samourai-Wallet:whirlpool-client:0.1.0')
and...
implementation ('com.github.Samourai-Wallet:extlibj:0.0.2')

This will be fixed for next release APK.

**Comment by int3hh** [comment]
works, thank you

**Comment by SamouraiDev** [comment]
Thank you for the feedback.
